import type { DiscoveryTest } from "./types";

export const MOCK_DISCOVERY_TESTS: DiscoveryTest[] = [
  {
    id: 1,
    title: "테스트 등록, 처음봐도 이해되나요?",
    description: "등록 흐름이 자연스러운지 피드백 부탁드려요.",
    reward: 300,
    thumbnailUrl: "https://static.toss.im/3d-emojis/u1F4F1.png",
    liked: true,
  },
  {
    id: 2,
    title: "운동 기록 탭 첫인상 테스트",
    description: "처음 봤을 때 어떤 기능인지 직관적으로 답해주세요.",
    reward: 500,
    thumbnailUrl: "https://static.toss.im/3d-emojis/u1F3C3.png",
    liked: false,
  },
  {
    id: 3,
    title: "커뮤니티 글쓰기, 5초 테스트",
    description: "이미지를 보고 어떤 서비스인지 기억나는 대로 답해주세요.",
    reward: 700,
    thumbnailUrl: "https://static.toss.im/3d-emojis/u1F4F8.png",
    liked: false,
  },
  {
    id: 4,
    title: "식단 서비스명, 첫인상이 어떤가요?",
    description: "서비스 이름이 건강하게 느껴지는지 솔직한 인상을 알려주세요.",
    reward: 200,
    thumbnailUrl: "https://static.toss.im/3d-emojis/u1F957.png",
    liked: false,
  },
  {
    id: 5,
    title: "판매자 신뢰도 판단 테스트",
    description: "대화 화면만 보고 거래를 이어갈지 빠르게 선택해 주세요.",
    reward: 1000,
    thumbnailUrl: "https://static.toss.im/3d-emojis/u1F4AC.png",
    liked: false,
  },
  {
    id: 7,
    title: "팀플 일정 조율, 바로 이해되나요?",
    description: "처음 봐도 핵심 기능이 바로 보이는지 확인해주세요.",
    reward: 400,
    thumbnailUrl: "https://static.toss.im/3d-emojis/u1F4C5.png",
    liked: false,
  },
  {
    id: 8,
    title: "반려동물 병원 찾기 지도 UX 테스트",
    description: "급할 때 가까운 병원을 빠르게 찾을 수 있는지 평가해주세요.",
    reward: 600,
    thumbnailUrl: "https://static.toss.im/3d-emojis/u1F436.png",
    liked: false,
  },
];
