export const ROUTES = {
  HOME: "/",
  DISCOVERY: "/discovery",
  DISCOVERY_GUIDE: "/discovery/guide",
  INTEREST: "/interest",
  INTEREST_DETAIL: "/interest/$testId",
  MY: "/my",
  MY_POLICY: "/my/policy",
  MY_PRIVACY: "/my/privacy",
  MY_BUSINESS: "/my/business",
  MY_PAYMENT_HISTORY: "/my/payment-history",
  TEST: "/test",
  TEST_CREATE: "/test/create",
  TEST_DRAFT_FAILED: "/test/draft/$draftId",
  TEST_DETAIL: "/test/$testId",
  TEST_PARTICIPATE: "/test/participate/$testId",
  TEST_PAYMENT: "/test/payment",
} as const;
